In [2]:
from builtins import range
from builtins import object
import numpy as np
from past.builtins import xrange

In [47]:
x = np.arange(8)
x = np.split(x, 4)
print(x)

folds =5 

for i in range(folds):
    X_tr = np.concatenate((x[:i]+x[i+1:]))
    print(X_tr)
    X_te = x[i]
    print(X_te)
 


[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]
[2 3 4 5 6 7]
[0 1]
[0 1 4 5 6 7]
[2 3]
[0 1 2 3 6 7]
[4 5]
[0 1 2 3 4 5]
[6 7]
[0 1 2 3 4 5 6 7]


IndexError: list index out of range